# Generated by Django 4.1.5 on 2024-02-27 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0023_remove_payment_booking_remove_payment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('StreetAddress', models.CharField(max_length=255)),
                ('Apartment', models.CharField(max_length=255)),
                ('TownCity', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Pin', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
