# Generated by Django 4.1.5 on 2024-02-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_checkout_booking_checkout_order_id_checkout_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='Apartment',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='Pin',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='State',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='StreetAddress',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='TownCity',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
