# Generated by Django 4.1.5 on 2024-03-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_checkout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='signature_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
