# Generated by Django 4.1.5 on 2024-03-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_checkout_signature_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='razorpay_payement_id',
            new_name='payement_id',
        ),
    ]
