# Generated by Django 4.1.5 on 2024-03-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_razorpay_payement_id_checkout_payement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='payement_id',
            new_name='payment_id',
        ),
    ]
