# Generated by Django 4.1.5 on 2024-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_checkout_paid_checkout_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
