# Generated by Django 4.1.5 on 2024-02-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_category_userprofile_shopprofile_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='house_name',
        ),
    ]
