# Generated by Django 4.1.5 on 2024-02-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_shopprofile_house_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
