# Generated by Django 4.1.5 on 2024-02-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_rename_user_id_shopprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
