# Generated by Django 4.1.5 on 2024-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_rename_user_id_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
