# Generated by Django 4.1.5 on 2024-02-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_category_category_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
