# Generated by Django 4.1.5 on 2024-02-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_rename_category_id_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_per_hour',
            new_name='price_per_day',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
