# Generated by Django 4.1.5 on 2024-02-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_rename_price_per_hour_product_price_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('W', 'Women'), ('M', 'Men'), ('A', 'Accessories')], default='W', max_length=1),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL'), ('5', 'XXL'), ('6', 'XXXL')], max_length=2)),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.product')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity_rented', models.PositiveIntegerField(default=1)),
                ('booking_status', models.CharField(choices=[('1', 'Booked'), ('2', 'Returned'), ('3', 'Cancelled'), ('4', 'Delivered')], max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.product')),
                ('productSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.productsize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
        ),
    ]
