# Generated by Django 4.1.5 on 2024-02-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_remove_product_availability_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='shopprofile',
            old_name='shop_description',
            new_name='shop_desc',
        ),
    ]
