# Generated by Django 4.1.5 on 2024-02-22 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
