# Generated by Django 4.1.5 on 2024-02-27 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_product_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('1', 'Booked'), ('2', 'Returned'), ('3', 'Cancelled'), ('4', 'Delivered'), ('5', 'Cart')], default=5, max_length=2),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('StreetAddress', models.CharField(max_length=255)),
                ('Apartment', models.CharField(max_length=255)),
                ('TownCity', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Pin', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
