# Generated by Django 4.1.5 on 2024-03-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('1', 'Booked'), ('2', 'Returned'), ('3', 'Cancelled'), ('4', 'Deliverd'), ('5', 'Initialised')], default=5, max_length=2),
        ),
    ]
